// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_starter = "CgkI9aemquYQEAIQAA"; // <GPGSID>
        public const string achievement_qub_slayer = "CgkI9aemquYQEAIQDg"; // <GPGSID>
        public const string achievement_cubenemy = "CgkI9aemquYQEAIQCw"; // <GPGSID>
        public const string achievement_7_at_a_time = "CgkI9aemquYQEAIQBA"; // <GPGSID>
        public const string achievement_fast_as_light = "CgkI9aemquYQEAIQBw"; // <GPGSID>
        public const string achievement_century_of_centuries = "CgkI9aemquYQEAIQBg"; // <GPGSID>
        public const string achievement_not_bad = "CgkI9aemquYQEAIQCQ"; // <GPGSID>
        public const string leaderboard_hall_of_qub = "CgkI9aemquYQEAIQDw"; // <GPGSID>
        public const string achievement_super_addict = "CgkI9aemquYQEAIQDQ"; // <GPGSID>
        public const string achievement_shameless = "CgkI9aemquYQEAIQAQ"; // <GPGSID>
        public const string achievement_6_at_a_time = "CgkI9aemquYQEAIQAw"; // <GPGSID>
        public const string achievement_rainbow_mania = "CgkI9aemquYQEAIQCA"; // <GPGSID>
        public const string achievement_cube_hunter = "CgkI9aemquYQEAIQCg"; // <GPGSID>
        public const string achievement_5_at_a_time = "CgkI9aemquYQEAIQAg"; // <GPGSID>
        public const string achievement_points_hunter = "CgkI9aemquYQEAIQBQ"; // <GPGSID>
        public const string achievement_ultimate_destroyer = "CgkI9aemquYQEAIQDA"; // <GPGSID>

}

